version: "3.1"

services:
  fe-app:
    image: lab3_fe_app
    container_name: lab3_fe_app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    working_dir: /app
    networks:
      - lab3_network

networks:
  lab3_network:
    driver: bridge
    external: true
